import { ArchitectureTemplate } from '../types/graph';

export const TEMPLATES: ArchitectureTemplate[] = [
  {
    id: 'ecommerce-distributed',
    name: 'E-Commerce Distributed Microservices',
    description: 'High-throughput e-commerce architecture with API Gateway, Redis caching, Kafka async messaging, and payment integration.',
    difficulty: 'Advanced',
    tags: ['Microservices', 'Kafka', 'Redis', 'PostgreSQL'],
    nodes: [
      {
        id: 'node-client-web',
        type: 'client',
        title: 'Web Storefront',
        subtitle: 'Next.js App Router',
        x: 80,
        y: 120,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 15,
        errorRate: 0,
        throughputRps: 450,
        color: '#38bdf8',
        iconName: 'Globe',
      },
      {
        id: 'node-client-mobile',
        type: 'client',
        title: 'Mobile App',
        subtitle: 'Flutter iOS / Android',
        x: 80,
        y: 280,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 25,
        errorRate: 0.2,
        throughputRps: 280,
        color: '#0ea5e9',
        iconName: 'Smartphone',
      },
      {
        id: 'node-gateway',
        type: 'gateway',
        title: 'API Gateway',
        subtitle: 'Kong / Envoy Ingress',
        x: 360,
        y: 200,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 8,
        errorRate: 0.05,
        throughputRps: 730,
        color: '#818cf8',
        iconName: 'Network',
      },
      {
        id: 'node-service-auth',
        type: 'service',
        title: 'Auth & User Service',
        subtitle: 'Node.js JWT / OAuth2',
        x: 640,
        y: 80,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 30,
        errorRate: 0.1,
        throughputRps: 300,
        color: '#a855f7',
        iconName: 'Server',
      },
      {
        id: 'node-service-order',
        type: 'service',
        title: 'Order Service',
        subtitle: 'Go gRPC Backend',
        x: 640,
        y: 220,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 40,
        errorRate: 0.4,
        throughputRps: 430,
        color: '#a855f7',
        iconName: 'Server',
      },
      {
        id: 'node-cache',
        type: 'cache',
        title: 'Session & Cache',
        subtitle: 'Redis Cluster',
        x: 920,
        y: 80,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 2,
        errorRate: 0,
        throughputRps: 1200,
        color: '#f43f5e',
        iconName: 'Cpu',
      },
      {
        id: 'node-db-orders',
        type: 'database',
        title: 'Orders Database',
        subtitle: 'PostgreSQL Primary',
        x: 920,
        y: 220,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 28,
        errorRate: 0.1,
        throughputRps: 410,
        color: '#3b82f6',
        iconName: 'Database',
      },
      {
        id: 'node-queue-kafka',
        type: 'queue',
        title: 'Order Events Bus',
        subtitle: 'Apache Kafka Topics',
        x: 640,
        y: 380,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 10,
        errorRate: 0.05,
        throughputRps: 850,
        color: '#f59e0b',
        iconName: 'Shuffle',
      },
      {
        id: 'node-worker-payment',
        type: 'service',
        title: 'Payment Processor',
        subtitle: 'Worker Consumer',
        x: 920,
        y: 380,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 60,
        errorRate: 0.8,
        throughputRps: 200,
        color: '#a855f7',
        iconName: 'Server',
      },
      {
        id: 'node-ext-stripe',
        type: 'external',
        title: 'Stripe Gateway',
        subtitle: 'External Payment API',
        x: 1200,
        y: 380,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 140,
        errorRate: 1.2,
        throughputRps: 190,
        color: '#10b981',
        iconName: 'ExternalLink',
      },
    ],
    edges: [
      { id: 'e1', fromNodeId: 'node-client-web', toNodeId: 'node-gateway', protocol: 'HTTP/REST', latencyMs: 25, errorRate: 0, label: '/api/v1' },
      { id: 'e2', fromNodeId: 'node-client-mobile', toNodeId: 'node-gateway', protocol: 'HTTP/REST', latencyMs: 35, errorRate: 0.1, label: '/api/v1' },
      { id: 'e3', fromNodeId: 'node-gateway', toNodeId: 'node-service-auth', protocol: 'gRPC', latencyMs: 8, errorRate: 0, label: 'verifyToken' },
      { id: 'e4', fromNodeId: 'node-gateway', toNodeId: 'node-service-order', protocol: 'gRPC', latencyMs: 12, errorRate: 0.2, label: 'createOrder' },
      { id: 'e5', fromNodeId: 'node-service-auth', toNodeId: 'node-cache', protocol: 'TCP', latencyMs: 2, errorRate: 0, label: 'GET /sessions' },
      { id: 'e6', fromNodeId: 'node-service-order', toNodeId: 'node-db-orders', protocol: 'SQL Query', latencyMs: 18, errorRate: 0.1, label: 'INSERT order' },
      { id: 'e7', fromNodeId: 'node-service-order', toNodeId: 'node-queue-kafka', protocol: 'Kafka', latencyMs: 6, errorRate: 0, label: 'orders.created' },
      { id: 'e8', fromNodeId: 'node-queue-kafka', toNodeId: 'node-worker-payment', protocol: 'Kafka', latencyMs: 5, errorRate: 0, label: 'consume' },
      { id: 'e9', fromNodeId: 'node-worker-payment', toNodeId: 'node-ext-stripe', protocol: 'HTTP/REST', latencyMs: 130, errorRate: 1.0, label: 'POST /charges' },
    ]
  },
  {
    id: 'ai-rag-pipeline',
    name: 'AI RAG & Vector Search Pipeline',
    description: 'Modern AI architecture with embedding generation, vector similarity search, and LLM synthesis.',
    difficulty: 'Intermediate',
    tags: ['AI / LLM', 'Vector DB', 'FastAPI', 'RAG'],
    nodes: [
      {
        id: 'ai-client',
        type: 'client',
        title: 'AI Chat Client',
        subtitle: 'Vercel AI SDK React',
        x: 100,
        y: 200,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 12,
        errorRate: 0,
        throughputRps: 60,
        color: '#38bdf8',
        iconName: 'Globe',
      },
      {
        id: 'ai-gateway',
        type: 'gateway',
        title: 'FastAPI Orchestrator',
        subtitle: 'Async Streaming Gateway',
        x: 380,
        y: 200,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 15,
        errorRate: 0.1,
        throughputRps: 60,
        color: '#818cf8',
        iconName: 'Network',
      },
      {
        id: 'ai-vector-db',
        type: 'database',
        title: 'Vector Database',
        subtitle: 'Pinecone / Qdrant Index',
        x: 680,
        y: 100,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 45,
        errorRate: 0.2,
        throughputRps: 180,
        color: '#3b82f6',
        iconName: 'Database',
      },
      {
        id: 'ai-llm-service',
        type: 'external',
        title: 'LLM Inference API',
        subtitle: 'Google Gemini 1.5 Pro',
        x: 680,
        y: 290,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 250,
        errorRate: 0.5,
        throughputRps: 55,
        color: '#10b981',
        iconName: 'ExternalLink',
      },
      {
        id: 'ai-storage',
        type: 'storage',
        title: 'Document S3 Bucket',
        subtitle: 'Raw PDFs & Embeddings',
        x: 980,
        y: 100,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 65,
        errorRate: 0.05,
        throughputRps: 40,
        color: '#14b8a6',
        iconName: 'HardDrive',
      },
    ],
    edges: [
      { id: 'ae1', fromNodeId: 'ai-client', toNodeId: 'ai-gateway', protocol: 'WebSocket', latencyMs: 20, errorRate: 0, label: 'stream:prompt' },
      { id: 'ae2', fromNodeId: 'ai-gateway', toNodeId: 'ai-vector-db', protocol: 'gRPC', latencyMs: 35, errorRate: 0, label: 'similarityQuery()' },
      { id: 'ae3', fromNodeId: 'ai-vector-db', toNodeId: 'ai-storage', protocol: 'TCP', latencyMs: 50, errorRate: 0, label: 'fetchChunks' },
      { id: 'ae4', fromNodeId: 'ai-gateway', toNodeId: 'ai-llm-service', protocol: 'HTTP/REST', latencyMs: 220, errorRate: 0.3, label: 'generate(context)' },
    ]
  },
  {
    id: 'websocket-realtime',
    name: 'Real-time WebSocket & Event Cluster',
    description: 'Scalable multi-node WebSocket server with Redis pub/sub backplane and event persistence.',
    difficulty: 'Intermediate',
    tags: ['WebSockets', 'PubSub', 'Redis', 'Scalability'],
    nodes: [
      {
        id: 'ws-client-1',
        type: 'client',
        title: 'Browser Client #1',
        subtitle: 'Active Web Session',
        x: 80,
        y: 120,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 18,
        errorRate: 0,
        throughputRps: 150,
        color: '#38bdf8',
        iconName: 'Globe',
      },
      {
        id: 'ws-client-2',
        type: 'client',
        title: 'Browser Client #2',
        subtitle: 'Active Web Session',
        x: 80,
        y: 280,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 22,
        errorRate: 0,
        throughputRps: 130,
        color: '#38bdf8',
        iconName: 'Globe',
      },
      {
        id: 'ws-lb',
        type: 'gateway',
        title: 'HAProxy / Nginx',
        subtitle: 'Sticky Session LB',
        x: 350,
        y: 200,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 6,
        errorRate: 0.05,
        throughputRps: 1200,
        color: '#818cf8',
        iconName: 'Network',
      },
      {
        id: 'ws-node-a',
        type: 'service',
        title: 'WS Gateway A',
        subtitle: 'Node.js Socket.IO',
        x: 620,
        y: 120,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 14,
        errorRate: 0.1,
        throughputRps: 600,
        color: '#a855f7',
        iconName: 'Server',
      },
      {
        id: 'ws-node-b',
        type: 'service',
        title: 'WS Gateway B',
        subtitle: 'Node.js Socket.IO',
        x: 620,
        y: 280,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 15,
        errorRate: 0.1,
        throughputRps: 600,
        color: '#a855f7',
        iconName: 'Server',
      },
      {
        id: 'ws-redis',
        type: 'cache',
        title: 'Redis Pub/Sub',
        subtitle: 'Message Backplane',
        x: 900,
        y: 200,
        width: 190,
        height: 90,
        status: 'healthy',
        latencyMs: 2,
        errorRate: 0,
        throughputRps: 5000,
        color: '#f43f5e',
        iconName: 'Cpu',
      },
    ],
    edges: [
      { id: 'we1', fromNodeId: 'ws-client-1', toNodeId: 'ws-lb', protocol: 'WebSocket', latencyMs: 15, errorRate: 0, label: 'wss://' },
      { id: 'we2', fromNodeId: 'ws-client-2', toNodeId: 'ws-lb', protocol: 'WebSocket', latencyMs: 15, errorRate: 0, label: 'wss://' },
      { id: 'we3', fromNodeId: 'ws-lb', toNodeId: 'ws-node-a', protocol: 'TCP', latencyMs: 5, errorRate: 0, label: 'route:client1' },
      { id: 'we4', fromNodeId: 'ws-lb', toNodeId: 'ws-node-b', protocol: 'TCP', latencyMs: 5, errorRate: 0, label: 'route:client2' },
      { id: 'we5', fromNodeId: 'ws-node-a', toNodeId: 'ws-redis', protocol: 'TCP', latencyMs: 2, errorRate: 0, label: 'PUBLISH /room' },
      { id: 'we6', fromNodeId: 'ws-redis', toNodeId: 'ws-node-b', protocol: 'TCP', latencyMs: 2, errorRate: 0, label: 'SUBSCRIBE' },
    ]
  }
];
